controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /{vueRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        vueRouting: .*
    defaults:
        vueRouting: null
